slider_mapping:
  0: master
  1: 
    - librewolf
    - alsa_playback.librewolf
    - chromium
    - brave
    - mpv
    - stremio
    - vlc
  2: deej.unmapped
  3: 
    - discord
    - vencord
    - vesktop
    - chromium
    - electron
invert_sliders: true

com_port: /dev/ttyUSB0
baud_rate: 9600

noise_reduction: default
